app_memorias/config/routes.rb
Rails.application.routes.draw do
  
  devise_for :comisions
  devise_for :coordinadors
  devise_for :administradors
  get 'welcome/index'
  devise_for :teachers
  devise_for :alumnos
  resources :topicos
  resources :evaluacions
  resources :tipo_correccions
  resources :mems do
    resources :documentacions, only: [:create, :destroy, :update]
    resources :correccions, only: [:create, :destroy, :update]
  end 
  resources :carreras
  resources :estados

  put "/mems/:id/asignar_guia", to: "mems#asignar_guia"
  put "/mems/:id/validar_formulario", to: "mems#validar_formulario"
  put "/mems/:id/aceptar", to: "mems#aceptar"
  put "/mems/:id/validar_avance", to: "mems#validar_avance"
  put "/mems/:id/corregir_avance", to: "mems#corregir_avance"
  put "/mems/:id/corregir_presentacion", to: "mems#corregir_presentacion"
  put "/mems/:id/validar_borrador", to: "mems#validar_borrador"
  put "/mems/:id/corregir_borrador", to: "mems#corregir_borrador"
  put "/mems/:id/esperar_encuesta", to: "mems#esperar_encuesta"
  put "/mems/:id/completar", to: "mems#completar"
  put "/mems/:id/cancelar", to: "mems#cancelar"
  put "/mems/:id/confirmar_cancelacion", to: "mems#confirmar_cancelacion"
  put "/mems/:id/rechazar_formulario", to: "mems#rechazar_formulario"
  put "/mems/:id/finalizar", to: "mems#finalizar"

  get "/perfil", to: "welcome#perfil"
  get "/profesores", to: "welcome#profesores"
  get "/alumns", to: "welcome#alum"
  get "/comisiones", to: "welcome#comisiones"
  get "/coordinadores", to: "welcome#coordinadores"

  get "/home/formularioTitulacion1", to: "mems#formularioTitulacion1"
  get "/home/formularioTitulacion2", to: "mems#formularioTitulacion2"

  root 'welcome#index'

end

app_memorias/app/models/mem.rb
class Mem < ActiveRecord::Base
  
  include AASM

  belongs_to :estado
  has_many :topico_asignados, dependent: :destroy
  has_many :topicos, through: :topico_asignados, dependent: :destroy
  has_many :documentacions, dependent: :destroy
  has_many :memorists, dependent: :destroy
  #validates :alumno_id, uniqueness: { scope: :mem_id, message: "Ya tienes una memoria asociada"}

  has_many :alumnos, through: :memorists, dependent: :destroy
  has_many :correctors, dependent: :destroy
  has_many :teachers, through: :correctors, dependent: :destroy
  has_many :correccions, dependent: :destroy

  after_create :save_topicos, :save_alumnos, :save_teachers

  after_update :save_correctores

  def topicos=(value)
  	@topicos = value
  end

  def alumnos=(value)
    @alumnos = value
  end

  def teachers=(value)
    @teachers = value
  end

  aasm column: "state" do
    state :creada, initial: true
    state :guia_asignado
    state :formulario_validado
    state :aceptada
    state :avance_validado
    state :avance_corregido
    state :presentacion_corregida
    state :borrador_validado
    state :borrador_corregido
    state :espera_encuesta
    state :completada
    state :dimitida
    state :cancelada
    state :finalizada

    event :asignar_guia do
      transitions from: :creada, to: :guia_asignado
    end

    event :validar_formulario do
      transitions from: :guia_asignado, to: :formulario_validado
    end

    event :rechazar_formulario do
      transitions from: :formulario_validado, to: :guia_asignado
    end

    event :aceptar do
      transitions from: :formulario_validado, to: :aceptada
    end
    
    event :validar_avance do
      transitions from: :aceptada, to: :avance_validado
    end

    event :corregir_avance do
      transitions from: :avance_validado, to: :avance_corregido
    end

    event :corregir_presentacion do
      transitions from: :avance_corregido, to: :presentacion_corregida
    end

    event :validar_borrador do
      transitions from: :presentacion_corregida, to: :borrador_validado
    end

    event :corregir_borrador do
      transitions from: :borrador_validado, to: :borrador_corregido
    end

    event :esperar_encuesta do
      transitions from: :borrador_corregido, to: :espera_encuesta
    end

    event :completar do
      transitions from: :espera_encuesta, to: :completada
    end

    event :finalizar do
      transitions from: :completada, to: :finalizada
    end

    event :cancelar do
      transitions from: [:creada, :guia_asignado, :formulario_validado, :aceptada, :avance_validado, :avance_corregido, :presentacion_corregida, :borrador_validado, :borrador_corregido, :espera_encuesta, :completada], to: :dimitida
    end

    event :confirmar_cancelacion do
      transitions from: :dimitida, to: :cancelada
    end
  end
  
  private 

  def save_teachers
    tipo_corrector = 1
    @teachers.each do|teacher_id|
      Corrector.create(teacher_id: teacher_id, mem_id: self.id, tipo_corector: tipo_corrector)
    end
  end

  def save_correctores
    tipo_corrector = 2
    if not @teachers.nil?
      @teachers.each do|teacher_id|
        Corrector.create(teacher_id: teacher_id, mem_id: self.id, tipo_corector: tipo_corrector)
      end
    end
  end

  def save_topicos
  	@topicos.each do|topico_id|
  	  TopicoAsignado.create(topico_id: topico_id, mem_id: self.id)
  	end
  end

  def save_alumnos
    @alumnos.each do|alumno_id|
      Memorist.create(alumno_id: alumno_id, mem_id: self.id)
    end
  end
end

app_memorias/app/controllers/mems_controller.rb
class MemsController < ApplicationController
  before_action :set_mem, only: [:show, :edit, :update, :destroy, :asignar_guia, :validar_formulario, :rechazar_formulario, :aceptar, :validar_avance, :corregir_avance, :corregir_presentacion, :validar_borrador, :corregir_borrador, :esperar_encuesta, :completar, :finalizar, :cancelar, :confirmar_cancelacion]

  # GET /mems
  # GET /mems.json
  def index
    @mems = Mem.all
    @alumnos = Alumno.all
    @estados = Estado.all
    @teachers = Teacher.all
     @correctors = Corrector.all
  end

  # GET /mems/1
  # GET /mems/1.json
  def show
    @documentacion = Documentacion.new
    @correccion = Correccion.new
    @topicos = Topico.all
    @alumnos = Alumno.all
    @estados = Estado.all
    @teachers = Teacher.all
    @correccions = Correccion.all
    @tipo_correccions = TipoCorreccion.all
    @correctors = Corrector.all
  end

  # GET /mems/new
  def new
    @mem = Mem.new
    @topicos = Topico.all
    @alumnos = Alumno.all
    @estados = Estado.all
    @teachers = Teacher.all
    @tipo_correccions = TipoCorreccion.all
  end

  # GET /mems/1/edit
  def edit
    @topicos = Topico.all
    @alumnos = Alumno.all
    @estados = Estado.all
    @teachers = Teacher.all
    @tipo_correccions = TipoCorreccion.all
  end

  # POST /mems
  # POST /mems.json
  def create
    @mem = Mem.new(mem_params)
    @mem.topicos = params[:topicos]
    @mem.alumnos = params[:alumnos]
    @mem.teachers = params[:teachers]

    respond_to do |format|
      if @mem.save
        format.html { redirect_to @mem, notice: 'Memoria creada correctamente.' }
        format.json { render :show, status: :created, location: @mem }
      else
        format.html { render :new }
        format.json { render json: @mem.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mems/1
  # PATCH/PUT /mems/1.json
  def update
    respond_to do |format|
      if @mem.update(mem_params)
        format.html { redirect_to @mem, notice: 'Memoria actualizada correctamente.' }
        format.json { render :show, status: :ok, location: @mem }
      else
        format.html { render :edit }
        format.json { render json: @mem.errors, status: :unprocessable_entity }
      end
    end
  end

  def asignar_guia
    @mem.asignar_guia!
    redirect_to @mem
  end

  def validar_formulario
    @mem.validar_formulario!
    redirect_to @mem
    flash.notice = "Memoria con formulario validado."
  end

  def aceptar
    @mem.aceptar!
    redirect_to @mem
    flash.notice = "Memoria aceptada."
  end

  def validar_avance
    @mem.validar_avance!
    redirect_to @mem
    flash.notice = "Memoria con avance validado."
  end

  def corregir_avance
    @mem.corregir_avance!
    redirect_to @mem
    flash.notice = "Memoria con avance corregido."
  end

  def corregir_presentacion
    @mem.corregir_presentacion!
    redirect_to @mem
    flash.notice = "Memoria con presentación corregida."
  end

  def validar_borrador
    @mem.validar_borrador!
    redirect_to @mem
    flash.notice = "Memoriacon borrador validado."
  end

  def corregir_borrador
    @mem.corregir_borrador!
    redirect_to @mem
    flash.notice = "Memoria con borrador corregido."
  end

  def esperar_encuesta
    @mem.esperar_encuesta!
    redirect_to @mem
    flash.notice = "Memoria esperando encuesta."
  end

  def completar
    @mem.completar!
    redirect_to @mem
    flash.notice = "Memoria completada."
  end

  def finalizar
    @mem.finalizar!
    redirect_to @mem
    flash.notice = "Memoria finalizada."
  end

  def cancelar
    @mem.cancelar!
    redirect_to @mem
    flash.notice = "Memoria en proceso de cancelación"
  end

  def confirmar_cancelacion
    @mem.confirmar_cancelacion!
    redirect_to @mem
    flash.notice = "Memoria cancelada."
  end

  def rechazar_formulario
    @mem.rechazar_formulario!
    redirect_to @mem
    flash.notice = "Formulario rechazado."
  end
  
  def formularioTitulacion1
    send_file(
      "#{Rails.root}/public/presentacion_proyecto_de_titulacion.pdf",
      filename: "presentacion_proyecto_de_titulacion.pdf",
      type: "application/pdf"
    )
  end

  def formularioTitulacion2
    send_file(
      "#{Rails.root}/public/solicitud_inscripcion_tema.pdf",
      filename: "solicitud_inscripcion_tema.pdf",
      type: "application/pdf"
    )
  end

  # DELETE /mems/1
  # DELETE /mems/1.json
  def destroy
    @mem.destroy
    respond_to do |format|
      format.html { redirect_to mems_url, notice: 'Memoria eliminada correctamente.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mem
      @mem = Mem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def mem_params
      params.require(:mem).permit(:titulo, :estado_id, :fecha_memoria, :fecha_avance, :fecha_defensa, :fecha_limimte, :topicos, :alumnos, :teachers, :resumen_ejecutivo)
    end
end

app_memorias/app/helpers/mems_helper.rb
module MemsHelper
end

app_memorias/app/views/mems/edit.html.erb
<div class="container">
  <div class="jumbotron">

       <%= form_for(@mem) do |f| %>
        <% if @mem.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@mem.errors.count, "error") %> prohibited this mem from being saved:</h2>
      
            <ul>
            <% @mem.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
            </ul>
          </div>
        <% end %>

        <% if coordinador_signed_in? %>
          <% if @mem.state == "avance_corregido" %>
            <h2>Editando Fecha Avance</h2>
            <div class="field">
              <%= f.label :fecha_avance %><br>
              <%= f.date_select :fecha_avance %>
            </div>
            <div class="actions">
              <%= f.submit class:"btn btn-primary active" %>
            </div>
          <% end %>
          <% if @mem.fecha_limimte.nil? %>
            <h2>Editando Fecha Límite</h2>
            <div class="field">
              <%= f.label :fecha_avance %><br>
              <%= f.date_select :fecha_avance %>
            </div>
            <div class="actions">
              <%= f.submit class:"btn btn-primary active" %>
            </div>
          <% end %>
          <% if @mem.state == "borrador_corregido" %>
            <h2>Editando Fecha de Defensa de Memoria</h2>
            <div class="field">
              <%= f.label :fecha_defensa %><br>
              <%= f.date_select :fecha_defensa %>
            </div>
            <div class="actions">
              <%= f.submit class:"btn btn-primary active" %>
            </div>
          <% end %>
        <% end %>

         <% if comision_signed_in? %>
          <% if @mem.state == "formulario_validado" %>
            <h2>Asignación de profesores correctores</h2>
            <div class="field">
              <label>Profesor Guia:</label><br>
              <div class="row">
                <% @teachers.each do |teacher| %>
                  <div class="col-md-3">
                    <%= check_box_tag "teachers[]", teacher.id %> <%= teacher.nombre %> <%= teacher.apellido %><br>
                  </div>
                <% end %>
              </div>
            </div>
            <div class="field">
              <%= f.label :resumen_ejecutivo %><br>
              <%= f.text_area :resumen_ejecutivo %>
            </div>
            <div class="actions">
              <%= f.submit class:"btn btn-primary active" %>
            </div>
          <% end %>
        <% end %>
      
        <% if alumno_signed_in? %>
        <h2>Editando Memoria</h2>
        <div class="field">
          <%= f.label :titulo %><br>
          <%= f.text_field :titulo %>
        </div>

        <div class="field">
          <%= f.label :resumen_ejecutivo %><br>
          <%= f.text_area :resumen_ejecutivo %>
        </div>

        <div class="field">
          <label>Tópicos</label><br>
          <div class="row">
            <% @topicos.each do |topico| %>
              <div class="col-md-3">
                <%= check_box_tag "topicos[]", topico.id %> <%= topico.nombre %><br>
              </div>
            <% end %>
          </div>
        </div>
        <div class="actions">
          <%= f.submit class:"btn btn-primary active" %>
        </div>
      <% end %>
      <% end %>
      
    <%= link_to 'Mostrar', @mem %> |
    <%= link_to 'Atrás', mems_path %>
  </div>
</div>

app_memorias/app/views/mems/new.html.erb
<div class="container">
  <div class="jumbotron">
    <h2>Nueva Memoria</h2>

    <%= render 'form' %>

    <%= link_to 'Atrás', mems_path %>
  </div>
</div>

app_memorias/app/views/mems/show.html.erb
<div class="container">
  <div class="jumbotron">
    <!--p id="notice"><%= notice %></p-->
    
    <h3><%= @mem.titulo %></h3>
    <br>

    <p>
      <span style="font-size:14px">
        <strong>Alumnos:</strong>
      </span>
    </p>
    <ul>
      <% @mem.alumnos.each do |alumno| %>
        <li>
          <span style="font-size:14px">
            <%= alumno.rut %>, <%= alumno.nombre %> <%= alumno.apellido %>
          </span>
        </li>
      <% end %>
    </ul>
    <br>

    <p>
      <span style="font-size:14px">
        <strong>Tópicos asociados a la memoria:</strong>
      </span>
    </p>
    <ul>
      <% @mem.topicos.each do |topico| %>
        <li>
          <span style="font-size:14px">
            <%= link_to topico.nombre, topico %>
          </span>
        </li>
      <% end %>
    </ul>
    <br>

    <div>
      <% if not @mem.resumen_ejecutivo.nil? %>
        <span style="font-size:14px">
          <strong>Resumen Ejecutivo:</strong><br>
          <%= @mem.resumen_ejecutivo %>
        </span> 
      <% end %>
    </div>
    <br>
    
    <p>
      <span style="font-size:14px">
        <strong>Estado:</strong>
        <% if @mem.state == "creada" %>
          Memoria creada
        <% elsif @mem.state == "guia_asignado" %>
          Profesor guía asignado
        <% elsif @mem.state == "formulario_validado" %>
          Formulario validado
        <% elsif @mem.state == "aceptada" %>
          Memoria aceptada
        <% elsif @mem.state == "avance_validado" %>
          Avance validado
        <% elsif @mem.state == "avance_corregido" %>
          Avance corregido
        <% elsif @mem.state == "presentacion_corregida" %>
          Presentación corregida
        <% elsif @mem.state == "borrador_validado" %>
          Borrador validado
        <% elsif @mem.state == "borrador_corregido" %>
          Borrador corregido
        <% elsif @mem.state == "espera_encuesta" %>
          En espera de encuesta
        <% elsif @mem.state == "completada" %>
          Memoria completada
        <% elsif @mem.state == "finalizada" %>
          Memoria finalizada
        <% elsif @mem.state == "cancelada" %>
          Memoria cancelada
        <% elsif @mem.state == "dimitida" %>
          Memoria en proceso de cancelación
        <% end %>
        <!--strong>Días Estado:</strong-->
        <!-- @mem.estado.dias -->
      </span>
    </p>
    
    <p>
      <span style="font-size:14px">
        <strong>Fecha memoria:</strong>
        <%= @mem.created_at %>
      </span>
    </p>
    
    <p>
      <span style="font-size:14px">
        <strong>Fecha avance:</strong>
        <% if @mem.fecha_avance.nil? %>
          No asignada
        <% else %>
          <%= @mem.fecha_avance %>
        <% end %>
      </span>
    </p>
    
    <p>
      <span style="font-size:14px">
        <strong>Fecha defensa:</strong>
        <% if @mem.fecha_defensa.nil? %>
          No asignada
        <% else %>
          <%= @mem.fecha_defensa %>
        <% end %>
      </span>
    </p>
    
    <p>
      <span style="font-size:14px">
        <strong>Fecha límite:</strong>
        <% if @mem.fecha_limimte.nil? %>
          No asignada
        <% else %>
          <%= @mem.fecha_limimte %>
        <% end %>
      </span>
    </p>
    <br>
      <% if alumno_signed_in? && (@mem.state == "creada" || @mem.state == "guia_asignado")%>
        <% @mem.alumnos.each do |alumno| %>
          <% if current_alumno.id == alumno.id %>
            <div class="row">
              <div class="col-md-1">
                <%= link_to 'Editar', edit_mem_path(@mem), class:"btn btn-default btn-xs" %>
              </div>
              <div>
                <span style="font-size:14px">
                  <%= link_to 'Cancelar Memoria', "/mems/#{@mem.id}/cancelar", class:"btn btn-default btn-xs", method: :put, data: { confirm: '¿Está seguro?' } %>
                </span>
              </div>
            </div>
          <% end %>
        <% end %>
      <% end %>
    <div>

    <% if alumno_signed_in? && @mem.may_completar? %>
        <%= link_to 'Responder Encuesta', new_evaluacion_path, class:"btn btn-default btn-xs" %>
      <% end %>

      <% if (administrador_signed_in? || comision_signed_in? || coordinador_signed_in?) && @mem.state == "cancelada" %>
        <%= link_to 'Eliminar', @mem, method: :delete, data: { confirm: '¿Está seguro?' }, class:"btn btn-default btn-xs" %> |
      <% end %>
    </div>
    
    <% if alumno_signed_in? && (@mem.state == "creada" || @mem.state == "guia_asignado") %>
      <hr>
      <div>
        <span style="font-size:16px">
          Descarga el formulario del proceso de titulación a continuación: <br><br>
          <strong>Formulario de Titulación: </strong>
          <br>
          <%= link_to 'presentacion_proyecto_de_titulacion.pdf', home_formularioTitulacion1_url %><br>
          <%= link_to 'solicitud_inscripcion_tema.pdf', home_formularioTitulacion2_url %>
        </span>
      </div>
      <hr>
    <% end %>

    <% if teacher_signed_in? %>
      <div class="row">
      <% if @mem.may_asignar_guia? %>
        <div class="col-md-offset-10">
          <span style="font-size:14px">
            <%= link_to 'Aceptar asignación', "/mems/#{@mem.id}/asignar_guia", class:"btn btn-default btn-xs", method: :put, data: { confirm: '¿Está seguro?' } %>
          </span>
        </div>
      <% end %>
      </div>
    <% end %>

    <br>
    <% if coordinador_signed_in? %>
      <% if @mem.fecha_limimte.nil? %>
        <div class="row">
          <div class="col-md-offset-10">
            <span style="font-size:14px">
              <%= link_to 'Asignar Fecha Límite', edit_mem_path(@mem), class:"btn btn-default btn-xs" %>
            </span>
          </div>
        </div>
        <br><br>
      <% end %>
      <% if @mem.may_completar? %>
        <div class="row">
          <div class="col-md-offset-10">
            <span style="font-size:14px">
              <%= link_to 'Pasar a memoria completada', "/mems/#{@mem.id}/completar", class:"btn btn-default btn-xs", method: :put, data: { confirm: '¿Está seguro?' } %>
            </span>
          </div>
        </div>
      <%end %>
      <% if @mem.may_finalizar? %>
        <div class="row">
          <div class="col-md-offset-8">
            <span style="font-size:14px">
              <%= link_to 'Realizar Pago a Profesores y Finalizar Memoria', "/mems/#{@mem.id}/finalizar", class:"btn btn-default btn-xs", method: :put, data: { confirm: '¿Está seguro?' } %>
            </span>
          </div>
        </div>
      <%end %>
      <% if @mem.may_esperar_encuesta? %>
        <div class="row">
          <div class="col-md-offset-10">
            <span style="font-size:14px">
              <%= link_to 'Pasar a Esperar Encuesta', "/mems/#{@mem.id}/esperar_encuesta", class:"btn btn-default btn-xs", method: :put, data: { confirm: '¿Está seguro?' } %>
            </span>
          </div>
        </div>
      <% end %>
      <% if @mem.fecha_avance.nil? && @mem.state == "avance_corregido" %>
        <div class="row">
          <div class="col-md-offset-10">
            <span style="font-size:14px">
              <%= link_to 'Asignar Fecha Avance', edit_mem_path(@mem), class:"btn btn-default btn-xs" %>
            </span>
          </div>
        </div>
      <% end %>
      <% if @mem.fecha_defensa.nil? && @mem.state == "borrador_corregido" %>
        <div class="row">
          <div class="col-md-offset-10">
            <span style="font-size:14px">
              <%= link_to 'Asignar Fecha Defensa', edit_mem_path(@mem), class:"btn btn-default btn-xs" %>
            </span>
          </div>
        </div>
      <% end %>
    <% end %>
    
    <div class="field">
      <h3>Documentaciones</h3>
      <br>
      <ul>
        <% @mem.documentacions.each do |documentacion| %>
          <li>
            <%= link_to documentacion.cover_file_name, documentacion.cover.url() %> -  <%= documentacion.updated_at %>
          </li>
        <% end %>
      </ul>
    </div>
    <% if (alumno_signed_in? && (@mem.state == "guia_asignado" || @mem.state == "aceptada" || @mem.state == "avance_corregido" || @mem.state =="presentacion_corregida" || @mem.state == "borrador_corregido")) %>
      <hr>
      <h4>Agregar Documentación</h4>
      <br>
      <%= render "documentacions/form" %>
      <hr>
      <br>
    <% end %>

     <% if (teacher_signed_in? && @mem.state == "avance_corregido")  %>
      <hr>
      <h4>Agregar Documentación</h4>
      <br>
      <%= render "documentacions/form" %>
      <hr>
      <br>
    <% end %>
    
    <% if teacher_signed_in? %>
      <div class="row">
      <% if @mem.may_validar_formulario? %>
        <div class="col-md-offset-10">
          <span style="font-size:14px">
            <% @mem.documentacions.each do |document| %>
            <% if not document.nil? %>
              <%= link_to 'Validar Formulario', "/mems/#{@mem.id}/validar_formulario", class:"btn btn-default btn-xs", method: :put, data: { confirm: '¿Está seguro?' } %>
            <% end %>
            <% end %>
          </span>
        </div>
      <% end %>
      <% if @mem.may_validar_avance? %>
        <div class="col-md-offset-10">
          <span style="font-size:14px">
            <%= link_to 'Validar Avance', "/mems/#{@mem.id}/validar_avance", class:"btn btn-default btn-xs", method: :put, data: { confirm: '¿Está seguro?' } %>
          </span>
        </div>
      <% end %>
      <% if @mem.may_corregir_avance? %>
        <% @mem.correccions.each do |correccion| %>
        <% if not correccion.nil? %>
        <div class="col-md-offset-10">
          <span style="font-size:14px">
            <%= link_to 'Pasar a Avance Corregido', "/mems/#{@mem.id}/corregir_avance", class:"btn btn-default btn-xs", method: :put, data: { confirm: '¿Está seguro?' } %>
          </span>
        </div>
        <% end %> <% end %>
      <% end %>
      <% if @mem.may_corregir_presentacion? %>
        <div class="col-md-offset-10">
          <span style="font-size:14px">
            <%= link_to 'Pasar a Presentación Corregida', "/mems/#{@mem.id}/corregir_presentacion", class:"btn btn-default btn-xs", method: :put, data: { confirm: '¿Está seguro?' } %>
          </span>
        </div>
      <% end %>
      <% if @mem.may_validar_borrador? %>
        <div class="col-md-offset-10">
          <span style="font-size:14px">
            <%= link_to 'Validar Borrador', "/mems/#{@mem.id}/validar_borrador", class:"btn btn-default btn-xs", method: :put, data: { confirm: '¿Está seguro?' } %>
          </span>
        </div>
      <% end %>
      <% if @mem.may_corregir_borrador? %>
        <div class="col-md-offset-10">
          <span style="font-size:14px">
            <%= link_to 'Pasar a Borrador Corregido', "/mems/#{@mem.id}/corregir_borrador", class:"btn btn-default btn-xs", method: :put, data: { confirm: '¿Está seguro?' } %>
          </span>
        </div>
      <% end %>
      <% if @mem.state == "dimitida" %>
        <div class="col-md-offset-10">
          <span style="font-size:14px">
            <%= link_to 'Confirmar Cancelación', "/mems/#{@mem.id}/confirmar_cancelacion", class:"btn btn-default btn-xs", method: :put, data: { confirm: '¿Está seguro?' } %>
          </span>
        </div>
      <% end %>
      </div>
    <% end %>

    <% if comision_signed_in? && @mem.state == "formulario_validado" %>
      <% if @mem.may_aceptar? %>
        <div class="row">
          <div class="col-md-offset-6 col-md-2">
            <span style="font-size:14px">
              <%= link_to 'Rechazar Formulario', "/mems/#{@mem.id}/rechazar_formulario", class:"btn btn-default btn-xs", method: :put, data: { confirm: '¿Está seguro?' } %>
            </span>
          </div>
          <div class="col-md-2">
            <span style="font-size:14px">
              <%= link_to 'Aceptar Memoria', "/mems/#{@mem.id}/aceptar", class:"btn btn-default btn-xs", method: :put, data: { confirm: '¿Está seguro?' } %>
            </span>
          </div>
          <div class="col-md-2">
            <span style="font-size:14px">
              <%= link_to 'Asignar Correctores', edit_mem_path(@mem) , class:"btn btn-default btn-xs" %>
            </span>
          </div>

        </div>
      <% end %>
    <% end %>

    <div class="field">

      <h3>Correcciones</h3>
      <br>
      <ul>
        <% @mem.correccions.each do |correccion| %>
          <li>
             <%= link_to correccion.cover_file_name, correccion.cover.url() %> - <%= correccion.ruta_correccion %> - <%= correccion.updated_at %>
          </li>
        <% end %>
      </ul>
    </div>
    <% if teacher_signed_in? && ( @mem.state == "avance_validado" || @mem.state == "avance_corregido" || @mem.state == "presentacion_corregida" || @mem.state == "borrador_validado") %>
      <hr>
      <h4>Agregar Corrección</h4>
      <br>
      <%= render "correccions/form" %>
      <hr>
      <br>
    <% end %>
    <br><br>
    <%= link_to 'Atrás', mems_path %>

  </div>
</div>