app_memorias/config/routes.rb
Rails.application.routes.draw do
  
  devise_for :comisions
  devise_for :coordinadors
  devise_for :administradors
  get 'welcome/index'
  devise_for :teachers
  devise_for :alumnos
  resources :topicos
  resources :evaluacions
  resources :tipo_correccions
  resources :mems do
    resources :documentacions, only: [:create, :destroy, :update]
    resources :correccions, only: [:create, :destroy, :update]
  end 
  resources :carreras
  resources :estados

  put "/mems/:id/asignar_guia", to: "mems#asignar_guia"
  put "/mems/:id/validar_formulario", to: "mems#validar_formulario"
  put "/mems/:id/aceptar", to: "mems#aceptar"
  put "/mems/:id/validar_avance", to: "mems#validar_avance"
  put "/mems/:id/corregir_avance", to: "mems#corregir_avance"
  put "/mems/:id/corregir_presentacion", to: "mems#corregir_presentacion"
  put "/mems/:id/validar_borrador", to: "mems#validar_borrador"
  put "/mems/:id/corregir_borrador", to: "mems#corregir_borrador"
  put "/mems/:id/esperar_encuesta", to: "mems#esperar_encuesta"
  put "/mems/:id/completar", to: "mems#completar"
  put "/mems/:id/cancelar", to: "mems#cancelar"
  put "/mems/:id/confirmar_cancelacion", to: "mems#confirmar_cancelacion"
  put "/mems/:id/rechazar_formulario", to: "mems#rechazar_formulario"
  put "/mems/:id/finalizar", to: "mems#finalizar"

  get "/perfil", to: "welcome#perfil"
  get "/profesores", to: "welcome#profesores"
  get "/alumns", to: "welcome#alum"
  get "/comisiones", to: "welcome#comisiones"
  get "/coordinadores", to: "welcome#coordinadores"

  get "/home/formularioTitulacion1", to: "mems#formularioTitulacion1"
  get "/home/formularioTitulacion2", to: "mems#formularioTitulacion2"

  root 'welcome#index'

end

app_memorias/app/models/evaluacion.rb
class Evaluacion < ActiveRecord::Base
  belongs_to :teacher
  belongs_to :alumno
  validates_inclusion_of :nota, :in => 1..7 , message: "La nota debe ir entre 1.0 y 7.0"
end

app_memorias/app/controllers/evaluacions_controller.rb
class EvaluacionsController < ApplicationController
  before_action :set_evaluacion, only: [:show, :edit, :update, :destroy]

  # GET /evaluacions
  # GET /evaluacions.json
  def index
    @evaluacions = Evaluacion.all
  end

  # GET /evaluacions/1
  # GET /evaluacions/1.json
  def show
  end

  # GET /evaluacions/new
  def new
    @evaluacion = Evaluacion.new
    @alumnos = Alumno.all
    @teachers = Teacher.all
    @mems = Mem.all
  end

  # GET /evaluacions/1/edit
  def edit
    @alumnos = Alumno.all
  end

  # POST /evaluacions
  # POST /evaluacions.json
  def create
    #@evaluacion = Evaluacion.new(evaluacion_params)
    @evaluacion = current_alumno.evaluacions.new(evaluacion_params)

    respond_to do |format|
      if @evaluacion.save
        format.html { redirect_to @evaluacion, notice: 'Evaluación realizada correctamente.' }
        format.json { render :show, status: :created, location: @evaluacion }
      else
        format.html { render :new }
        format.json { render json: @evaluacion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /evaluacions/1
  # PATCH/PUT /evaluacions/1.json
  def update
    respond_to do |format|
      if @evaluacion.update(evaluacion_params)
        format.html { redirect_to @evaluacion, notice: 'Evaluacion was successfully updated.' }
        format.json { render :show, status: :ok, location: @evaluacion }
      else
        format.html { render :edit }
        format.json { render json: @evaluacion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /evaluacions/1
  # DELETE /evaluacions/1.json
  def destroy
    @evaluacion.destroy
    respond_to do |format|
      format.html { redirect_to evaluacions_url, notice: 'Evaluacion was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_evaluacion
      @evaluacion = Evaluacion.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def evaluacion_params
      params.require(:evaluacion).permit(:teacher_id, :alumno_id, :nota)
    end
end

app_memorias/app/helpers/evaluacions_helper.rb
module EvaluacionsHelper
end

app_memorias/app/views/evaluacions/_form.html.erb
<%= form_for(@evaluacion) do |f| %>
  <% if @evaluacion.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@evaluacion.errors.count, "error") %> prohibited this evaluacion from being saved:</h2>

      <ul>
      <% @evaluacion.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <label>Profesor:</label><br>
    <%= collection_select( :evaluacion, :teacher_id, Teacher.all, :id, :rut, {}) %>
  </div>
  <div class="field">
  La evaluación realizada por el profesor ¿es acorde a las correcciones del proyecto de título?<br><br>
    <%= f.label :nota %><br>
    <%= f.text_field :nota %>
  </div>
  <div class="actions">
    <%= f.submit class:"btn btn-primary active" %>
  </div>
<% end %>

app_memorias/app/views/evaluacions/edit.html.erb
<div class="container">
  <div class="jumbotron">
    <h2>Editando Evaluación</h2>

    <%= render 'form' %>

    <%= link_to 'Mostrar', @evaluacion %> |
    <%= link_to 'Atrás', evaluacions_path %>
  </div>
</div>

app_memorias/app/views/evaluacions/index.html.erb
<div class="container">
  <div class="jumbotron">
    <!--p id="notice"><%= notice %></p-->
    
    <h2>Lista de Evaluaciones</h2>
    <br>
    <div class="row">
      <div class="col-md-2">
        <span style="font-size:14px">
          <strong>Profesor</strong>
        </span>
      </div>
      <div class="col-md-2">
        <span style="font-size:14px">
          <strong>Alumno</strong>
        </span>
      </div>
      <div class="col-md-1">
        <span style="font-size:14px">
          <strong>Nota</strong>
        </span>
      </div>
      <div class="col-md-2">
        <span style="font-size:14px">
          <strong>Fecha</strong>
        </span>
      </div>
    </div>
    <hr>
    <% @evaluacions.each do |evaluacion| %>
      <div class="row">
        <div class="col-md-2">
          <span style="font-size:14px">
            <%= evaluacion.teacher.rut %>
          </span>
        </div>
        <div class="col-md-2">
          <span style="font-size:14px">
            <%= evaluacion.alumno.rut %>
          </span>
        </div>
        <div class="col-md-1">
          <span style="font-size:14px">
            <%= link_to evaluacion.nota, evaluacion %>
          </span>
        </div>
        <div class="col-md-3">
          <span style="font-size:14px">
            <%= evaluacion.updated_at %>
          </span>
        </div>
        <div class="col-md-1">
          <span style="font-size:14px">
            <%= link_to 'Editar', edit_evaluacion_path(evaluacion), class:"btn btn-default btn-xs" %>
          </span>
        </div>
        <div>
          <span style="font-size:14px">
            <%= link_to 'Eliminar', evaluacion, method: :delete, data: { confirm: '¿Está seguro?' }, class:"btn btn-default btn-xs" %>
          </span>
        </div>
      </div>
      <hr>
    <% end %>
    
    <br>
    
    <%= link_to 'Nueva Evaluación', new_evaluacion_path, class:"btn btn-default btn-xs" %>
  </div>
</div>
    

app_memorias/app/views/evaluacions/new.html.erb
<div class="container">
  <div class="jumbotron">
    <h2>Nueva Evaluación</h2>

    <%= render 'form' %>

    <%= link_to 'Atrás', evaluacions_path %>
  </div>
</div>

app_memorias/app/views/evaluacions/show.html.erb
<div class="container">
  <div class="jumbotron">
    <p id="notice"><%= notice %></p>
    
    <p>
      <span style="font-size:14px">
        <strong>Profesor:</strong>
        <%= @evaluacion.teacher.rut %>, <%= @evaluacion.teacher.nombre %> <%= @evaluacion.teacher.apellido %>
      </span>
    </p>
    
    <p>
      <span style="font-size:14px">
        <strong>Alumno:</strong>
        <%= @evaluacion.alumno.rut %>, <%= @evaluacion.alumno.nombre %> <%= @evaluacion.alumno.apellido %>
      </span>
    </p>
    
    <p>
      <span style="font-size:14px">
        <strong>Nota:</strong>
        <%= @evaluacion.nota %>
      </span>
    </p>

    <p>
      <span style="font-size:14px">
        <strong>Fecha:</strong>
        <%= @evaluacion.updated_at %>
      </span>
    </p>
    
    <%= link_to 'Editar', edit_evaluacion_path(@evaluacion) %> |
    <%= link_to 'Atrás', evaluacions_path %>
  </div>
</div>