app_memorias/config/routes.rb
Rails.application.routes.draw do
  
  devise_for :comisions
  devise_for :coordinadors
  devise_for :administradors
  get 'welcome/index'
  devise_for :teachers
  devise_for :alumnos
  resources :topicos
  resources :evaluacions
  resources :tipo_correccions
  resources :mems do
    resources :documentacions, only: [:create, :destroy, :update]
    resources :correccions, only: [:create, :destroy, :update]
  end 
  resources :carreras
  resources :estados

  put "/mems/:id/asignar_guia", to: "mems#asignar_guia"
  put "/mems/:id/validar_formulario", to: "mems#validar_formulario"
  put "/mems/:id/aceptar", to: "mems#aceptar"
  put "/mems/:id/validar_avance", to: "mems#validar_avance"
  put "/mems/:id/corregir_avance", to: "mems#corregir_avance"
  put "/mems/:id/corregir_presentacion", to: "mems#corregir_presentacion"
  put "/mems/:id/validar_borrador", to: "mems#validar_borrador"
  put "/mems/:id/corregir_borrador", to: "mems#corregir_borrador"
  put "/mems/:id/esperar_encuesta", to: "mems#esperar_encuesta"
  put "/mems/:id/completar", to: "mems#completar"
  put "/mems/:id/cancelar", to: "mems#cancelar"
  put "/mems/:id/confirmar_cancelacion", to: "mems#confirmar_cancelacion"
  put "/mems/:id/rechazar_formulario", to: "mems#rechazar_formulario"
  put "/mems/:id/finalizar", to: "mems#finalizar"

  get "/perfil", to: "welcome#perfil"
  get "/profesores", to: "welcome#profesores"
  get "/alumns", to: "welcome#alum"
  get "/comisiones", to: "welcome#comisiones"
  get "/coordinadores", to: "welcome#coordinadores"

  get "/home/formularioTitulacion1", to: "mems#formularioTitulacion1"
  get "/home/formularioTitulacion2", to: "mems#formularioTitulacion2"

  root 'welcome#index'

end

app_memorias/app/models/topico.rb
class Topico < ActiveRecord::Base
  validates :nombre, presence: true
  has_many :topico_asignados, dependent: :destroy
  has_many :mems, through: :topico_asignados, dependent: :destroy
  #has_many :topico_teachers
  #has_many :teachers, through: :topico_teachers
end

app_memorias/app/controllers/topicos_controller.rb
class TopicosController < ApplicationController
  before_action :set_topico, only: [:show, :edit, :update, :destroy]

  # GET /topicos
  # GET /topicos.json
  def index
    @topicos = Topico.all
  end

  # GET /topicos/1
  # GET /topicos/1.json
  def show
  end

  # GET /topicos/new
  def new
    @topico = Topico.new
  end

  # GET /topicos/1/edit
  def edit
  end

  # POST /topicos
  # POST /topicos.json
  def create
    @topico = Topico.new(topico_params)

    respond_to do |format|
      if @topico.save
        format.html { redirect_to @topico, notice: 'Tópico creado correctamente.' }
        format.json { render :show, status: :created, location: @topico }
      else
        format.html { render :new }
        format.json { render json: @topico.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /topicos/1
  # PATCH/PUT /topicos/1.json
  def update
    respond_to do |format|
      if @topico.update(topico_params)
        format.html { redirect_to @topico, notice: 'Tópico actualizado correctamente.' }
        format.json { render :show, status: :ok, location: @topico }
      else
        format.html { render :edit }
        format.json { render json: @topico.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /topicos/1
  # DELETE /topicos/1.json
  def destroy
    @topico.destroy
    respond_to do |format|
      format.html { redirect_to topicos_url, notice: 'Tópico eliminado correctamente.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_topico
      @topico = Topico.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def topico_params
      params.require(:topico).permit(:nombre)
    end
end

app_memorias/app/helpers/topicos_helper.rb
module TopicosHelper
end

app_memorias/app/views/topicos/_form.html.erb
<%= form_for(@topico) do |f| %>
  <% if @topico.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@topico.errors.count, "error") %> prohibited this topico from being saved:</h2>

      <ul>
      <% @topico.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br>
    <%= f.text_field :nombre %>
  </div>
  <div class="actions">
    <%= f.submit class:"btn btn-primary active" %>
  </div>
<% end %>

app_memorias/app/views/topicos/edit.html.erb
<div class="container">
  <div class="jumbotron">
    <h2>Editando Tópico</h2>

    <%= render 'form' %>

    <%= link_to 'Mostrar', @topico %> |
    <%= link_to 'Atrás', topicos_path %>
  </div>
</div>

app_memorias/app/views/topicos/index.html.erb
<div class="container">
  <div class="jumbotron">
    <!--p id="notice"><%= notice %></p-->
    
    <h2>Lista de Tópicos</h2>
    <hr>
    <% @topicos.each do |topico| %>
      <div class="row">
        <div class="col-md-3">
          <span style="font-size:14px">
            <%= topico.id %>.
            <%= link_to topico.nombre, topico %>
          </span>
        </div>
        <div class="col-md-1">
          <span style="font-size:14px">
            <%= link_to 'Editar', edit_topico_path(topico), class:"btn btn-default btn-xs" %>
          </span>
        </div>
        <!--div class="col-md-1">
          <span style="font-size:14px">
            <%= link_to 'Eliminar', topico, method: :delete, data: { confirm: '¿Está seguro?' }, class:"btn btn-default btn-xs" %>
          </span>
        </div-->
      </div>
      <hr>
    <% end %>
    
    <br>
    
    <%= link_to 'Nuevo Tópico', new_topico_path, class:"btn btn-default btn-xs" %>
  </div>
</div>

app_memorias/app/views/topicos/new.html.erb
<div class="container">
  <div class="jumbotron">
    <h2>Nuevo Tópico</h2>

    <%= render 'form' %>

    <%= link_to 'Atrás', topicos_path %>
  </div>
</div>

app_memorias/app/views/topicos/show.html.erb
<div class="container">
  <div class="jumbotron">
    <!--p id="notice"><%= notice %></p-->
    
    <p>
      <span style="font-size:14px">
        <strong>Nombre Tópico:</strong>
        <%= @topico.nombre %>
      </span>
    </p>
    <br>
    <p>
      <span style="font-size:14px">
        <strong>Lista de Memorias Asociadas:</strong>
      </span>
    </p>
    <hr>
    <% @topico.mems.each do |mem| %>
      <div>
        <span style="font-size:14px">
          <%= link_to mem.titulo, mem %>
        </span>
          <%= link_to "Ver más...", memclass:"btn btn-default btn-xs" %>
      </div>
      <hr>
    <% end %>
    <br>

    
    <%= link_to 'Editar', edit_topico_path(@topico) %> |
    <%= link_to 'Atrás', topicos_path %>
  </div>
</div>